name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: []

    steps:
    - name: Deploy to k8s
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.K8S_HOST }}
        username: ubuntu
        key: ${{ secrets.K8S_SSH_KEY }}
        script: |
          kubectl rollout restart deployment/hello-app
